jupyterlite/xeus-python-kernel

- package.json
- pyproject.toml
- setup.py
- src/worker.ts
- webpack.config.js
@DerThorsten Trying locally, removing the sleep(2000) seems to not impact xeus-python-kernel's behavior?
> Remove sleep + renames according to https://github.com/jupyter-xeus/xeus-python/pull/530

- Dockerfile
cc. @DerThorsten @jtpio
Adding Matplotlib to the env, this way people can use it.
This is probably temporary, until we have a way to install packages with mamba.
> Add Matplotlib to the env

- MANIFEST.in
- setup.py
> Reduce sdist size

- jupyterlite_xeus_python/env_build_addon.py
This should fix the `jupyter lite build` command that is waiting infinitely when run via sphinx-build.
> Fix hanging jupyterlite build via jupyterlite-sphinx

- .github/workflows/build.yml
- CHANGELOG.md
- docs/environment.yml
- docs/jupyterlite_config.json
- environment.yml
- src/worker.ts
* this adds a bugfix which blocks the execution of the next cell until the previous one is done (when executed together) 
* see https://github.com/jupyter-xeus/xeus-python/pull/543
> Toplevel await

- jupyterlite_xeus_python/env_build_addon.py
Fix #22
- Fix incompatibility issue when there is a common labextension between the user prefix and the xeus-python-env prefix (e.g. ipyleaflet is installed in both), starting with this PR the labextension from xeus-python-env takes priority.
- Always install the jupyterlite-xeus-python extension even if `ignore_sys_prefix` is enabled.
> Fix conflicts with sys prefix packages and ignore ignore_sys_prefix flag

- .gitignore
- MANIFEST.in
- README.md
- package.json
- pyproject.toml
- src/index.ts
- src/worker.ts
- src/xeus_server_kernel.ts
- worker.webpack.config.js
- yarn.lock
Also use comlink for the worker communication, like jupyterlite does with Pyolite.
Fixes #26
> Update jupyterlite and enable file-system access

- jupyterlite_xeus_python/env_build_addon.py
This fixes an issue when the core FederatedExtension addon runs first
> Fix post_build so that it populates the jupyter-lite.json properly

- src/index.ts
Set the plugin id to `@jupyterlite/xeus-python-kernel-extension:kernel` to avoid collisions with other xeus based kernels, which would otherwise result in plugin activation errors:
> Fix plugin id

- src/index.ts
Simplify the kernel spec now that https://github.com/jupyterlite/jupyterlite/pull/657 has been released.
> Simplify the kernel spec

- jupyterlite_xeus_python/env_build_addon.py
Fix issue mentioned in https://github.com/benbovy/ipytone/pull/78#issuecomment-1168467713
It might not be possible to upstream these changes to jupyterlite while removing them here, because the doit task "patch" must be of a different name in order to run on the xeus-python post-build.
> Add a deduplication phase that make sure the latest copied labextension is used

- docs/index.rst
A small thing but there seems to be an extra leading space with the default example in the documentation: https://xeus-python-kernel.readthedocs.io/en/latest/
> Remove leading space in the replite default example

- src/xeus_server_kernel.ts
Minor typo fix: `initFileSytem` -> `initFileSystem`
> Fix typo in `initFileSystem` method name

- CHANGELOG.md
Automated Changelog Entry for 0.5.4 on main
After merging this PR run the "Full Release" Workflow on your fork of `jupyter_releaser` with the following inputs
| Input  | Value |
| ------------- | ------------- |
| Target | jupyterlite/xeus-python-kernel  |
| Branch  | main  |
| Version Spec | 0.5.4 |
| Since | v0.5.3 |
> Automated Changelog Entry for 0.5.4 on main

- CHANGELOG.md
Automated Changelog Entry for 0.5.5 on main
After merging this PR run the "Full Release" Workflow on your fork of `jupyter_releaser` with the following inputs
| Input  | Value |
| ------------- | ------------- |
| Target | jupyterlite/xeus-python-kernel  |
| Branch  | main  |
| Version Spec | 0.5.5 |
| Since | v0.5.4 |
> Automated Changelog Entry for 0.5.5 on main

- CHANGELOG.md
Automated Changelog Entry for 0.5.6 on main
After merging this PR run the "Full Release" Workflow on your fork of `jupyter_releaser` with the following inputs
| Input  | Value |
| ------------- | ------------- |
| Target | jupyterlite/xeus-python-kernel  |
| Branch  | main  |
| Version Spec | 0.5.6 |
| Since | v0.5.5 |
> Automated Changelog Entry for 0.5.6 on main

- Dockerfile
I was trying to build the docker image on a Mac but kept getting libmamba "cannot find requested empack" errors. Turns out it was because docker was defaulting to using a linux aarch64 image which doesn't have packages available on the mamba channels. Solved it by specifying the linux/amd64 platform such that docker should use that image and its corresponding packages. Maybe other platforms are supported? Any ideas to not force emulating linux/amd64 are welcome. Nevertheless seems like a good default just in case.
> Specify linux/amd64 for docker image

- .github/workflows/check-release.yml
- package.json
- pyproject.toml
Investigate releaser workflow failures: https://github.com/jupyterlite/xeus-python-kernel/actions/runs/4185862759
> Update to `check-release@v2`

- docs/build-environment.yml
- docs/jupyter-lite.json
- jupyterlite_xeus_python/env_build_addon.py
- setup.py
- tests/test_xeus_python_env.py
The core functionality of the `jupyterlite` package is being extracted to a new `jupyterlite-core` package in https://github.com/jupyterlite/jupyterlite/pull/994.
This will allow site deployers to make slimmer deployments without having to bring the Pyodide kernel as well.
And let them use alternative kernels like Xeus Python only if they want to.
> Depend on `jupyterlite-core`

- docs/build-environment.yml
- docs/jupyter-lite.json
- setup.py
Update to the latest `jupyterlite-core`: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0b20
Which does not include the JavaScript kernel by default anymore: https://github.com/jupyterlite/jupyterlite/pull/1013
The JavaScript kernel should not be available by default on the demo site in the docs.
None
> Update to `jupyterlite-core==0.1.0b20`

- .github/workflows/build.yml
- .github/workflows/check-release.yml
- jupyterlite_xeus_python/env_build_addon.py
This will help resolve the issue that Voici needs a specific ipywidgets lab extension in the page
> Provide a way for Voici to pin packages

- README.md
- docs/build-environment.yml
- docs/conf.py
- docs/configuration.md
- docs/environment.yml
- jupyterlite_xeus_python/build.py
- jupyterlite_xeus_python/env_build_addon.py
- setup.py
- tests/test_xeus_python_env.py
Would fix #100 and probably fix https://github.com/jupyterlite/xeus-python-kernel/issues/48
This is very much experimental for now.
Pip is running with the `--no-deps` option, meaning that the user would need to install the package dependencies from conda-forge/emscripten-forge/PyPI themselves.
Pip is not made for installing packages in another environment (it is supposed to install packages for the Python version it uses, nothing else), so we have to workaround this by doing some shenanigans to make it work. The `--no-deps` option is one of those workarounds.
I don't think we should support reading some `requirements.txt` file for now, at least not before pip packages are more correctly supported, if they ever are.
> Add support for pip dependencies

- jupyterlite_xeus_python/build.py
- tests/test_package/environment-3.yml
- tests/test_package/pyproject.toml
- tests/test_package/test_package/hey.py
- tests/test_xeus_python_env.py
This would fix issues for when the environment file is not at the same location as where we are running jupyterlite
> Compute local package dir when pip install

- .github/workflows/build.yml
The previous action is deprecated so we can update to the maintained one:
> Use `mamba-org/setup-micromamba` GitHub Action

- package.json
I was hoping to fix the errors that happen whenever jupyterlite gets released and then we have packages out of sync (like in https://github.com/jupyterlite/pyodide-kernel/pull/55)
But I see that the pyodide kernel is also sharing those dependencies properly.
So I don't know if this patch will make things better in the future, at least it won't be harmful.
> Make sure to share all packages coming from jupyterlite

- .github/workflows/build.yml
Follow-up to https://github.com/jupyterlite/xeus-python-kernel/pull/157.
There were a couple more places that were still referencing `conda-incubator/setup-miniconda`.
> Use `mamba-org/setup-micromamba` in more places

- .github/workflows/enforce-label.yml
To be sure to not miss adding the GitHub label, so the generated changelog is nicely formatted.
> Add `enforce-label` workflow

- .github/workflows/build.yml
- pyproject.toml
Fix https://github.com/jupyterlite/xeus-python-kernel/issues/177.
Which could be related to https://github.com/jupyterlite/xeus-python-kernel/pull/168
> Add missing `ensured-targets`

- docs/build-environment.yml
- jupyterlite_xeus_python/env_build_addon.py
- setup.py
> Support both jupyterlite 0.1 and 0.2
